#pragma once

#include <array>
#include <cstdint>
#include <filesystem>
#include <vector>

#include <gsl/gsl>

#include <LuminolRenderEngine/Graphics/BoundingBox.hpp>
#include <LuminolRenderEngine/Graphics/TexturePaths.hpp>
#include <LuminolRenderEngine/Graphics/SDL_GPU/SDL_GPUBuffer.hpp>
#include <LuminolRenderEngine/Graphics/SDL_GPU/SDL_GPUTexture.hpp>
#include <LuminolRenderEngine/Utilities/ImageLoader.hpp>
#include <LuminolRenderEngine/Utilities/ModelLoader.hpp>

namespace Luminol::Graphics::SDL_GPU {

class GPUDevice;
class RenderPass;
class CopyPass;
class CommandBuffer;

// LOD0 = full detail ... LOD(max_lod_levels - 1) = coarsest. Shared by mesh
// loading (LOD generation), the GPU cull pass (per-instance LOD selection),
// and the render passes that draw per-LOD indirect commands.
inline constexpr auto max_lod_levels = std::size_t{4};

// A LOD level's draw range into a submesh's shared index buffer - all LOD
// levels of a submesh reference the same vertex range (vertex_offset),
// since simplification only selects a subset of existing vertices rather
// than creating new ones.
struct LodRange {
    uint32_t first_index;
    uint32_t index_count;
};

// A LOD level's slice of a submesh's shared meshlet arrays (see
// RenderableMeshes::meshlet_metadata_buffer et al. and
// SDL_GPUMeshletCullPass) - not a contiguous index range like LodRange,
// since meshlets are looked up by index into meshlet_metadata_buffer, not
// drawn as a vertex/index range directly.
struct MeshletRange {
    uint32_t first_meshlet;
    uint32_t meshlet_count;
};

// One ~64-vertex/~64-triangle cluster of a submesh's geometry at one LOD
// level, generated by meshopt_buildMeshlets (see load_meshes_from_model).
// vertex_offset/triangle_offset are absolute offsets into the renderable's
// shared meshlet_vertices_buffer / meshlet_triangles_buffer (baked at load
// time - callers never need a separate per-submesh base). bounds_center is
// local-space (transformed by each instance's model matrix at cull time,
// like SDL_GPUMesh::local_bounds); bounds_radius is in the same local
// units. 32 bytes, already a multiple of the 16-byte StructuredBuffer
// element stride (see SDL_GPUInstanceCullPass.cpp's SubmeshCullMetadata for
// why that multiple matters) - no padding field needed.
struct GpuMeshletMetadata {
    uint32_t vertex_offset;
    uint32_t triangle_offset;
    uint32_t vertex_count;
    uint32_t triangle_count;
    std::array<float, 3> bounds_center;
    float bounds_radius;
};

struct TextureImages {
    std::optional<Utilities::ImageLoader::Image> diffuse_texture;
    Utilities::ModelLoader::TextureWrap diffuse_texture_wrap;
    std::optional<Utilities::ImageLoader::Image> normal_texture;
    Utilities::ModelLoader::TextureWrap normal_texture_wrap;
    std::optional<Utilities::ImageLoader::Image> metallic_texture;
    Utilities::ModelLoader::TextureWrap metallic_texture_wrap;
    std::optional<Utilities::ImageLoader::Image> roughness_texture;
    Utilities::ModelLoader::TextureWrap roughness_texture_wrap;
    std::optional<Utilities::ImageLoader::Image> ambient_occlusion_texture;
    Utilities::ModelLoader::TextureWrap ambient_occlusion_texture_wrap;
    Utilities::ModelLoader::AlphaMode alpha_mode =
        Utilities::ModelLoader::AlphaMode::Opaque;

    // True when roughness_texture / ambient_occlusion_texture come from the
    // same source file as metallic_texture (e.g. glTF's packed
    // occlusion/roughness/metallic convention) - lets SDL_GPUMesh reuse
    // metallic_texture's already-uploaded GPU texture instead of uploading
    // the same pixel data again.
    bool roughness_shares_metallic_source = false;
    bool ambient_occlusion_shares_metallic_source = false;
};

// A submesh's draw parameters into its renderable's shared vertex/index
// buffers (see RenderableMeshes) - not owned buffers of its own, so several
// submeshes can be batched into a single indirect multi-draw call sharing
// one bound vertex/index buffer.
class SDL_GPUMesh {
public:
    SDL_GPUMesh(
        GPUDevice& device,
        CopyPass& copy_pass,
        const std::array<LodRange, max_lod_levels>& lod_ranges,
        const std::array<MeshletRange, max_lod_levels>& meshlet_ranges,
        int32_t vertex_offset,
        const BoundingBox& local_bounds,
        const TexturePaths& texture_paths
    );

    SDL_GPUMesh(
        GPUDevice& device,
        CopyPass& copy_pass,
        const std::array<LodRange, max_lod_levels>& lod_ranges,
        const std::array<MeshletRange, max_lod_levels>& meshlet_ranges,
        int32_t vertex_offset,
        const BoundingBox& local_bounds,
        const TextureImages& texture_images
    );

    // Caller must have already bound this mesh's renderable's shared
    // vertex/index buffers (see RenderableMeshes) on sdl_gpu_pass.
    auto draw(RenderPass& sdl_gpu_pass) const -> void;
    auto draw_instanced(int32_t instance_count, RenderPass& sdl_gpu_pass) const
        -> void;

    // Issues the draw call without binding material samplers. Used by passes
    // whose fragment shader doesn't sample any of this mesh's material
    // textures (e.g. the SSAO normal prepass). Caller must have already
    // bound this mesh's renderable's shared vertex/index buffers.
    auto draw_instanced_geometry_only(
        int32_t instance_count, RenderPass& sdl_gpu_pass
    ) const -> void;

    // Issues one indexed indirect draw command read from indirect_buffer at
    // byte_offset without binding material samplers (see
    // SDL_GPUInstanceCullPass - the command's num_instances is written by a
    // GPU culling compute pass, not known on the CPU; and
    // draw_instanced_geometry_only). Caller must have already bound this
    // mesh's renderable's shared vertex/index buffers.
    auto draw_indirect_geometry_only(
        RenderPass& sdl_gpu_pass,
        const Buffer& indirect_buffer,
        uint32_t byte_offset
    ) const -> void;

    // Binds this mesh's material samplers, then issues one non-indexed
    // indirect draw command read from indirect_buffer at byte_offset (see
    // RenderPass::draw_primitives_indirect) - used by the main color pass's
    // meshlet vertex-pull path (SDL_GPUMeshletCullPass,
    // pbr_vert_meshlet.hlsl), which manually fetches geometry via
    // SV_VertexID/SV_InstanceID instead of a bound vertex/index buffer.
    // Caller must not have any vertex/index buffer bound for this draw.
    auto draw_meshlet_indirect(
        RenderPass& sdl_gpu_pass,
        const Buffer& indirect_buffer,
        uint32_t byte_offset
    ) const -> void;

    [[nodiscard]] auto alpha_mode() const -> Utilities::ModelLoader::AlphaMode;

    // LOD0's draw range - used by the non-indirect draw paths (CPU-sorted
    // transparent submeshes, point/spot shadow instancing), which don't
    // participate in GPU LOD selection.
    [[nodiscard]] auto get_first_index() const -> uint32_t;
    [[nodiscard]] auto get_index_count() const -> uint32_t;
    [[nodiscard]] auto get_vertex_offset() const -> int32_t;

    [[nodiscard]] auto get_lod_range(std::size_t lod_index) const
        -> const LodRange&;

    // This LOD level's slice of the renderable's shared meshlet arrays (see
    // RenderableMeshes) - used by SDL_GPUMeshletCullPass to build its
    // per-(instance,meshlet) cull dispatch for the main color pass only.
    [[nodiscard]] auto get_meshlet_range(std::size_t lod_index) const
        -> const MeshletRange&;

    // Local-space bounding box derived from vertex positions at construction
    // time, used for CPU-side frustum culling (e.g. per-light shadow pass
    // draw skipping).
    [[nodiscard]] auto get_local_bounds() const -> const BoundingBox&;

    // Generates mip chains for the material textures. Must be called outside
    // any render/copy pass on command_buffer.
    auto generate_mipmaps(CommandBuffer& command_buffer) const -> void;

private:
    std::array<LodRange, max_lod_levels> lod_ranges;
    std::array<MeshletRange, max_lod_levels> meshlet_ranges;
    int32_t vertex_offset;
    BoundingBox local_bounds;

    Texture diffuse_texture;
    Texture normal_texture;
    Texture metallic_texture;
    Texture roughness_texture;
    Texture ambient_occlusion_texture;

    Sampler diffuse_sampler;
    Sampler normal_sampler;
    Sampler metallic_sampler;
    Sampler roughness_sampler;
    Sampler ambient_occlusion_sampler;

    Utilities::ModelLoader::AlphaMode mesh_alpha_mode =
        Utilities::ModelLoader::AlphaMode::Opaque;
};

// A renderable's shared vertex/index buffers plus its submeshes, each of
// which only stores draw-parameter offsets into these shared buffers (see
// SDL_GPUMesh). Sharing one buffer pair per renderable lets all of its
// submeshes be drawn via a single bound vertex/index buffer, which is
// required for indirect multi-draw batching (SDL_GPUPointSpotShadowPass).
struct RenderableMeshes {
    Buffer vertex_buffer;
    Buffer index_buffer;
    // Shared meshlet arrays for this renderable, one entry-set per submesh
    // per LOD level (see SDL_GPUMesh::get_meshlet_range, GpuMeshletMetadata).
    // Only consumed by SDL_GPUMeshletCullPass / the main color pass's
    // vertex-pull vertex shader - every other pass keeps using
    // vertex_buffer/index_buffer above unchanged.
    Buffer meshlet_metadata_buffer;
    Buffer meshlet_vertices_buffer;
    Buffer meshlet_triangles_buffer;
    std::vector<SDL_GPUMesh> meshes;
};

// Axis-aligned bounding box over vertex positions (first 3 of the 11-float
// vertex stride: position, uv, normal, tangent), used for CPU-side frustum
// culling. Tighter than a bounding sphere for large flat/elongated meshes
// (e.g. building floors/walls), where a sphere's radius would be close to
// the shape's full diagonal.
[[nodiscard]] auto compute_mesh_local_bounds(gsl::span<const float> vertices)
    -> BoundingBox;

[[nodiscard]] auto load_meshes_from_model(
    GPUDevice& device, const std::filesystem::path& model_path
) -> RenderableMeshes;

// Builds meshlets for one already-finalized (vertex-cache-optimized) index
// buffer, appending them to the renderable-wide combined meshlet arrays with
// absolute offsets/indices baked in (see GpuMeshletMetadata), and returns
// the resulting MeshletRange. Exposed (not just load_meshes_from_model-local)
// so SDL_GPUFactory::create_mesh's procedural-geometry path can build real
// meshlets too - every submesh drawn through the main color pass needs valid
// meshlet data, not just model-loaded ones (see SDL_GPUMeshletCullPass).
// vertex_positions_stride is in bytes (matches meshoptimizer's own
// convention); submesh_vertex_offset is added to every meshlet_vertices
// entry so it's an absolute index into the renderable's combined vertex
// buffer, matching LodRange/vertex_offset's existing convention.
[[nodiscard]] auto build_meshlets(
    gsl::span<const uint32_t> indices,
    gsl::span<const float> vertex_positions,
    std::size_t vertex_count,
    std::size_t vertex_positions_stride,
    uint32_t submesh_vertex_offset,
    std::vector<GpuMeshletMetadata>& combined_meshlets,
    std::vector<uint32_t>& combined_meshlet_vertices,
    std::vector<uint32_t>& combined_meshlet_triangles
) -> MeshletRange;

}  // namespace Luminol::Graphics::SDL_GPU
